In [3]:
import numpy as np
size = 50
A = np.random.randn(size)
B = np.random.randn(size)
C = A + B
print("The maximum is: %.2f" % C.max())
print("The minimum is: %.2f" % C.min())
print("The sum is: %.2f" % C.sum())
print("The mean is: %.2f" % C.mean())
print("The number of negative values is:",np.where(C < 0, 1, 0).sum())

The maximum is: 2.53
The minimum is: -3.73
The sum is: 0.85
The mean is: 0.02
The number of negative values is: 24


In [8]:
A = np.random.randn(5,4)
print("The original matrix:")
print(A)
print("The maximum values for each row:",A.max(axis=1))
print("The maximum values for each column:",A.max(axis=0))
print("The minimum values for each row:",A.min(axis=1))
print("The minimum values for each column:",A.min(axis=0))
print("The sub-matrix:")
print(A[2:,1:])

The original matrix:
[[-0.51373126  0.46485833  1.06457611  0.43061197]
 [ 0.51865803  0.49556617 -0.31360386 -1.82972146]
 [-1.37862047 -2.64920942 -1.06687806  1.7668747 ]
 [ 0.00599944  1.26478725  1.14934367  0.24129907]
 [ 1.56476518  1.11108426 -0.48779628  0.15126816]]
The maximum values for each row: [1.06457611 0.51865803 1.7668747  1.26478725 1.56476518]
The maximum values for each column: [1.56476518 1.26478725 1.14934367 1.7668747 ]
The minimum values for each row: [-0.51373126 -1.82972146 -2.64920942  0.00599944 -0.48779628]
The minimum values for each column: [-1.37862047 -2.64920942 -1.06687806 -1.82972146]
The sub-matrix:
[[-2.64920942 -1.06687806  1.7668747 ]
 [ 1.26478725  1.14934367  0.24129907]
 [ 1.11108426 -0.48779628  0.15126816]]


In [10]:
A = np.random.randn(10,10)
print("The sum of all the positive values is %.2f" %(A * (A>0)).sum())
print("The sum of all the negative values is %.2f" % (A * (A<0)).sum())

The sum of all the positive values is 46.52
The sum of all the negative values is -37.17
